// Generated by https://quicktype.io

class Popularmodel {
  String? backdropPath;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  double? voteAverage;
  int? voteCount;

  Popularmodel({
    this.backdropPath,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.voteAverage,
    this.voteCount,
  });

  factory Popularmodel.fromMap(Map<String, dynamic> map) {
    return Popularmodel(
        backdropPath: map['backdropPath'],
        id: map['id'],
        originalLanguage: map['originalLanguage'],
        originalTitle: map['originalTitle'],
        overview: map['overview'],
        popularity: map['popularity'],
        posterPath: map['posterPath'],
        releaseDate: map['releaseDate'],
        title: map['title'],
        voteAverage: map['voteAverage'],
        voteCount: map['voteCount']);
  }
}
